### PR TITLE
fix: Fixed the hiding behavior of sidebar with footer in Documentation.vue

### LINKED ISSUE #908: Scrollbar Issue: Last Two Topics ('Daily Dumps' & 'Data Policy') Not Navigating Properly
**Describe the bug**
When navigating to any topic in the scrollbar, it works fine except for the last two topics: "Daily Dumps" and "Data Policy". The scrollbar does not function as expected for these two topics.

**Steps to Reproduce**
1. Open the application and navigate to the topic list.
2. Scroll through and select any topic except the last two – works fine.
3. Try selecting "Daily Dumps" or "Data Policy".
4. Observe that the scrollbar behavior is inconsistent or buggy.

**Expected behavior**
The scrollbar should work smoothly for all topics, including the last two.

**Screenshots**

https://github.com/user-attachments/assets/07f0551f-8f0e-490b-a4f7-324a5e69c775

### PR DESCRIPTION
**Pull request by sahitya-chandra**
## Description

1. Fixed the hiding of the sidebar with the footer when we scroll to the end of the Documentation page.
2. Removed the 'QDrawer' for better and controlled behavior of the Sidebar and made it hidden on the small screen.
3. Structured CSS in proper order.

## Related issue

fixed #908 

## How Has This Been Tested?

I have tested all the changes locally.

## Screenshots (if appropriate):

[Screencast from 2025-02-17 15-21-42.webm](https://github.com/user-attachments/assets/cdc9a756-d809-4c3e-90c7-ac391fb19c63)

[Screencast from 2025-02-17 16-14-06.webm](https://github.com/user-attachments/assets/4f33fab4-2249-461a-a2f4-b4df4d49165c)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sahitya-chandra** [comment]
@dpgiakatos Sir please review this code...

**Review by dpgiakatos — CHANGES_REQUESTED** [review]
This PR deletes the QDrawer and re-implements it. However, the contributor should have used the existing QDrawer and fixed the issue instead of deleting and re-implementing it. We don't need to reinvent the wheel, as this approach will take too much time for maintenance. Thus, this PR needs a lot of changes and should continue to use Quasar components.

**Comment by sahitya-chandra** [comment]
@dpgiakatos Sir Due to the implicit behavior of QDrawer it has infinite height because of this I have re-implemented the sidebar for static behavior.
Can I use any other Quasar component other than QDrawer if need be?

**Comment by dpgiakatos** [comment]
Yes, you can use other quasar components.

**Comment by sahitya-chandra** [comment]
@dpgiakatos Sir I have added the QSplitter component and organized the CSS in proper order. Removed multiple media-query.
Please review the code and let me know if there is any scope for correction.

[Screencast from 2025-02-18 11-15-30.webm](https://github.com/user-attachments/assets/7a0cb4bf-4576-4259-a91f-d5a1bc7b0994)

**Comment by sahitya-chandra** [comment]
Also Sir, I have not deleted any code just organised it.

File: src/views/Documentation.vue [hunk 1]
```diff
@@ -135,72 +134,74 @@ const sectionActive = ref('')
 </script>
 
 <template>
-  <div>
-    <QDrawer v-model="showSidebar" side="left" bordered class="IHR_documentation-page-sidebar">
-      <h3>{{ $t('documentationPage.title') }}</h3>
-      <div v-for="(sec, idx) in sections" :key="idx">
-        <div class="text-weight-light">
-          {{ $t(`documentationPage.sectionsTitle.${sec.sectionsTitle}`) }}
+  <QSplitter>
```
Comment (dpgiakatos) [inline src/views/Documentation.vue:137]: You haven't configured the component. You have to ad the `v-model`.
Also, add `disable` property.
Read the documentation:
https://quasar.dev/vue-components/splitter

**Review by dpgiakatos — CHANGES_REQUESTED** [review]
Address my inline comment. Additionally, I would like the page to have the same behavior as the old version. Previously, when scrolling to a section, the contents would be visible on the right. In this version, you have to scroll to the top to see them. I would like to restore the same behavior as the old page, where the contents are visible on the right when scrolling to a section.

File: src/views/Documentation.vue (hunk 1 above)
Comment (sahitya-chandra) [reply src/views/Documentation.vue:137]: @dpgiakatos Sir Where should I add `disable` property...

Comment (sahitya-chandra) [reply src/views/Documentation.vue]: @dpgiakatos Sir as you mentioned above to achieve old version behavior. 
 I have removed the QSplitter component because it was causing problems with anchor navigation and 
 I have added QCard and QCardSection for proper navigation and better scrolling of Sidebar.

**Comment by sahitya-chandra** [comment]
This the current behavior. 

[Screencast from 2025-02-18 18-54-19.webm](https://github.com/user-attachments/assets/c1e11727-ddea-47d9-b08a-abe6dadc3591)

**Comment by sahitya-chandra** [comment]
Sir I have also removed multiple media queries to reduce redundancy in the code.

**Review by dpgiakatos — APPROVED** [review]
Thanks

**Comment by sahitya-chandra** [comment]
Thanks for approving my changes Sir...🚀
